export const USER_STATE_CHANGE = 'USER_STATE_CHANGE';

//AUTH
export const CREATE_USER_START = 'CREATE_USER_START';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOGOUT_START = 'USER_LOGOUT_START';
export const USER_LOGOUT_FAILED = 'USER_LOGOUT_FAILED';


export const FETCH_NOTIFICATIONS = 'FETCH_NOTIFICATIONS';
export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION';
export const DELETE_ALL_NOTIFICATIONS = 'DELETE_ALL_NOTIFICATIONS';

export const FETCH_WODS = 'FETCH_WODS';

export const FETCH_WORKOUTS = 'FETCH_WORKOUTS';
export const FETCH_WORKOUTS_FAILED = 'FETCH_WORKOUTS_FAILED';

export const ADD_WORKOUT_START = 'ADD_WORKOUT_START';
export const ADD_WORKOUT_FINISH = 'ADD_WORKOUT_FINISH';
export const ADD_WORKOUT_FAILED = 'ADD_WORKOUT_FAILED';
export const DELETE_WORKOUT = 'DELETE_WORKOUT';

export const ADD_WOD_START = 'ADD_WOD_START';
export const ADD_WOD_FINISH = 'ADD_WOD_FINISH';
export const ADD_WOD_FAILED = 'ADD_WOD_FAILED';

export const FETCH_HOMEDATA = 'FETCH_HOMEDATA';
export const FETCH_HOMEDATA_FAILED = 'FETCH_HOMEDATA_FAILED';

export const FETCH_HEALTH = 'FETCH_HEALTH';